### PR TITLE
Docker image and Docker compose file

### PR DESCRIPTION
**Pull request by sezan92**
This PR adds a `Dockerfile` and a `docker-compose` file to run the Review Object detection metrics GUI in any linux environment.  I built the docker and run in my environment. I haven't tested it for Windows.

### How to test

In a terminal,  please run

```shell
xhost +local:
```

then run the following 

```shell
docker compose up
```

The GUI should show up.

### CODE REVIEW

**Comment by sezan92** [comment]
@rafaelpadilla  as mentioned in #122 I made PR for Docker containeration. please check. please let me know if any other information is needed.

**Comment by sezan92** [comment]
@rafaelpadilla can you check?

**Comment by sezan92** [comment]
@rafaelpadilla can you tell me why you closed this PR ?

**Comment by rafaelpadilla** [comment]
Hey @sezan92 ,

I didn't close it. The autobot is closing it.
This PR is super important !!!! :100:  I need time to review and test this PR.
This feature is super relevant and I really appreciate your contribution :pray: :smiley:

**Comment by sezan92** [comment]
@rafaelpadilla oh thanks.

**Pull request closed without merging**
